// Generated by https://pagedraw.io/pages/5837
import Topbar from './topbar';
import React from 'react';
import './home.css';

function render() {
    return <div className="home">
        <div className="home-0">
            <div className="home-home-3">
                <div className="home-0-0-0">
                    <div className="home-instance_of_deleted_component-6">
                        <Topbar title={"This is my home page!"} /> 
                    </div>
                </div>
                <div className="home-0-0-1">
                    <div className="home-0-0-1-0" /> 
                    <div className="home-text-7">Hello world</div>
                    <div className="home-0-0-1-2" /> 
                </div>
                <div className="home-0-0-2" /> 
            </div>
        </div>
    </div>;
};

export default function(props) {
    return render.apply({props: props});
}