// Generated by https://pagedraw.io/pages/5837
import Topbar from './topbar';
import React from 'react';
import './other.css';

function render() {
    return <div className="other">
        <div className="other-0">
            <div className="other-other-9">
                <div className="other-0-0-0">
                    <div className="other-instance_of_deleted_component-4">
                        <Topbar title={"This is my other page!"} /> 
                    </div>
                </div>
                <div className="other-0-0-1">
                    <div className="other-0-0-1-0" /> 
                    <img src="https://ucarecdn.com/1d4e6f52-2e8f-4058-bf6c-edf2e6f950a5/" className="other-image_2" /> 
                    <div className="other-0-0-1-2" /> 
                </div>
                <div className="other-0-0-2" /> 
                <div className="other-0-0-3">
                    <div className="other-0-0-3-0" /> 
                    <img src="https://ucarecdn.com/b2d70f42-09d5-42fb-8393-92ecda987049/" className="other-image-4" /> 
                </div>
            </div>
        </div>
    </div>;
};

export default function(props) {
    return render.apply({props: props});
}